export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="bg-blue-300 m-5 h-12 rounded-xl p-2">Header</div>
        </header>
        {children}
        <footer className="bg-black text-white m-5 h-12 rounded-xl p-2">
          footer
        </footer>
      </body>
    </html>
  );
}
